In [71]:
import numpy as np
from itertools import product

def generate_matrices1(n):
    if n % 2 == 1:
        num_ones = n**2 // 2
        num_zeros = num_ones + 1
    else:
        num_zeros = num_ones = n**2 // 2

    valid_matrices = []
    for p in product([0, 1], repeat=n**2):
        if p.count(0) == num_zeros and p.count(1) == num_ones:
            matrix = [p[i:i+n] for i in range(0, len(p), n)]
            valid_matrices.append(matrix)
    return valid_matrices

def generate_matrices2(n):
    if n % 2 == 1:
        num_zeros = n**2 // 2
        num_ones = num_zeros + 1
    else:
        num_ones = num_zeros = n**2 // 2

    valid_matrices = []
    for p in product([0, 1], repeat=n**2):
        if p.count(0) == num_zeros and p.count(1) == num_ones:
            matrix = [p[i:i+n] for i in range(0, len(p), n)]
            valid_matrices.append(matrix)
    return valid_matrices

#set the size of the matrix
n = 4
matrices1 = generate_matrices1(n)

matrices2 = generate_matrices2(n)
    
#calculate the determinants of the matrices
det1 = []
for matrix1 in matrices1:
    det1.append(np.linalg.det(matrix1))

det2 = []
for matrix2 in matrices2:
    det2.append(np.linalg.det(matrix2))
    
if n%2==1:
    print(2*len(det1))
else:
    print(len(det1))

#calculate the probability of producing a matrix with a determinant of 0 when Player 0 goes first 
prob1 = det1.count(0)/len(det1)
print(prob1)

#calculate the probability of producing a matrix with a determinant of 0 when Player 1 goes first
prob2 = det2.count(0)/len(det2)
print(prob2)


12870
0.586013986013986
0.586013986013986


In [68]:
# importing Numpy package 
import numpy as np 
  
# creating a 3,3 Numpy matrix 
n_array = np.array([[1,0,0,1], [0,0,1,1], [0,1,1,0],[0,1,0,1]]) 
  
# Displaying the Matrix 
print("Numpy Matrix is:") 
print(n_array) 
  
# calculating the determinant of matrix 
det = np.linalg.det(n_array) 
  
print("\nDeterminant of given 4X4 matrix:") 
print(int(det)) 

Numpy Matrix is:
[[1 0 0 1]
 [0 0 1 1]
 [0 1 1 0]
 [0 1 0 1]]

Determinant of given 4X4 matrix:
-2


In [69]:
import numpy as np
from math import comb

#calculates the total number of possible matrics 
for n in range(1,11):
    if n%2==0:
        result = comb(n**2, n**2//2)
    else:
        result = 2*comb(n**2, (n**2 +1)//2)
    
    print(result)
    

2
6
252
12870
10400600
9075135300
126410606437752
1832624140942590534
424784580848791721628840
100891344545564193334812497256
